# Generated by Django 5.1.7 on 2025-12-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lost', models.BooleanField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location_text', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_method', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
